In [238]:
import numpy as np

In [239]:
def dot_product(x, w, b):
    return np.dot(x, w) + b

In [240]:
def relu(x):
    return np.maximum(0, x)

def relu_derivatives(x):
    x[x<=0] = 0
    x[x>0] = 1
    return x

In [241]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivatives(x):
    return sigmoid(x) * (1-  sigmoid(x))

In [242]:
def linear(x):
    return x

def linear_derivatives(x):
    return 1

In [243]:
def loss_function(prediction, target):
    return 0.5 * np.power((prediction -  target), 2)

def loss_function_derivatives(prediction, target):
    return 2 * 0.5 *(prediction - target)

In [244]:
# inisiasi variable
i = np.array([[2]])

wij = np.array([[0.25, 0.5, 0.75, 1]])
bij = np.array([[1, 1, 1, 1]])

wjk = np.array([[1, 0], [0.75, 0.25], [0.5, 0.5], [0.25, 0.75]])
bjk = np.array([[1, 1]])

wko = np.array([[1], [0.5]])
bko = np.array([[1]])

o = np.array([[3]])

In [245]:
# forward pass input layer to hidden layer1
jin = dot_product(i, wij, bij)
jout = relu(jin)
print(jin)
print(jout)

[[ 1.5  2.   2.5  3. ]]
[[ 1.5  2.   2.5  3. ]]


In [246]:
# forward pass hidden layer1 to hidden layer2
kin = dot_product(jout, wjk, bjk)
kout = sigmoid(kin)
print(kin)
print(kout)

[[ 6.  5.]]
[[ 0.99752738  0.99330715]]


In [247]:
# forward pass hidden layer2 to output layer
oin = dot_product(kout, wko, bko)
oout = linear(oin)
print(oin)
print(oout)

[[ 2.49418095]]
[[ 2.49418095]]


In [248]:
# hitung loss
loss = loss_function(oout, o)
print(loss)

[[ 0.12792645]]


In [249]:
# mulai back pass
# back pass output to hidden layer1
# chain rules
# turunan_loss terhadap turunan_wko = turunan_loss terhadap turunan_oout * turunan_oout terhadap turunan_oin * turunan_oin terhadap turunan_wko

In [250]:
# hitung turunan loss terhadap turunan oout
turunan_loss_oout = loss_function_derivatives(oout, o)
turunan_loss_oout

array([[-0.50581905]])

In [251]:
# hitung turunan oout terhadap oin
# oout == ooin
turunan_oout_oin = linear_derivatives(oout)
turunan_oout_oin

1

In [252]:
# hitung turunan oin terhadap wko
turunan_oin_wko = kout.T
turunan_oin_wko

array([[ 0.99752738],
       [ 0.99330715]])

In [253]:
# hitung turunan loss terhadap wko
turunan_loss_wko = turunan_loss_oout * turunan_oout_oin * turunan_oin_wko
turunan_loss_wko

array([[-0.50456835],
       [-0.50243368]])

In [254]:
# hitung turunan loss terhadap bo
turunan_loss_bko = turunan_loss_oout * turunan_oout_oin * bko
turunan_loss_bko

array([[-0.50581905]])

In [255]:
# update variable wko
turunan_wko = wko - (np.array([[0.25]]) * turunan_loss_wko)
turunan_wko

array([[ 1.12614209],
       [ 0.62560842]])

In [256]:
# update variable bko
turunan_bko = bko - (np.array([[0.25]]) * turunan_loss_bko)
turunan_bko

array([[ 1.12645476]])

In [257]:
# backpass hidden layer2 to hidden layer1
# chain rules
# turunan loss terhadap wjk = turunan loss terhadap turunan kout * turunan kout terhadap turunan kin * turunan kin terhadap turunan wjk

In [258]:
# hitung turunana loss terhadap turunan kout
# rumus
turunan_loss_kout = (turunan_loss_oout * turunan_oout_oin * turunan_oin_wko * wko).T
turunan_loss_kout

array([[-0.50456835, -0.25121684]])

In [259]:
# hitung turunan kout terhadap turunan kin
turunan_kout_kin = sigmoid_derivatives(kin)
turunan_kout_kin

array([[ 0.00246651,  0.00664806]])

In [260]:
# hitung turunan kin terhadap turunan wjk
turunan_kin_wjk = np.concatenate((jout.T, jout.T), axis=1)
turunan_kin_wjk

array([[ 1.5,  1.5],
       [ 2. ,  2. ],
       [ 2.5,  2.5],
       [ 3. ,  3. ]])

In [261]:
# hitung turunan loss terhadap wjk
turunan_loss_wjk = turunan_loss_kout * turunan_kout_kin * turunan_kin_wjk
turunan_loss_wjk

array([[-0.00186678, -0.00250516],
       [-0.00248905, -0.00334021],
       [-0.00311131, -0.00417526],
       [-0.00373357, -0.00501031]])

In [262]:
# hitung turunan loss terhadap bjk
turunan_loss_bjk = turunan_loss_kout * turunan_kout_kin * bjk
turunan_loss_bjk

array([[-0.00124452, -0.0016701 ]])

In [263]:
# update variable wjk
turunan_wjk = wjk - (0.25 * turunan_loss_wjk)
turunan_wjk

array([[  1.00046670e+00,   6.26288917e-04],
       [  7.50622261e-01,   2.50835052e-01],
       [  5.00777827e-01,   5.01043815e-01],
       [  2.50933392e-01,   7.51252578e-01]])

In [264]:
# update variable bjk
turunan_bjk = bjk - (0.25 * turunan_loss_bjk)
turunan_bjk

array([[ 1.00031113,  1.00041753]])

In [265]:
# back pass hidden layer1 to input
# chain rules
# turunanan loss terhadap wij = turunan loss terhadap turunan jout * turunan jout terhadap turunan jin * turunan jin terhadap turunan wij

In [266]:
# hitung turunan loss terhadap turunan jout
turunan_loss_jout = np.sum(turunan_loss_kout) * np.sum(turunan_kout_kin) * np.sum(turunan_kin_wjk, axis=1) * np.sum(turunan_wjk, axis=1)
turunan_loss_jout

array([-0.02068855, -0.02759477, -0.03450601, -0.04142227])

In [268]:
# hitung turunan jout terhadap turunan jin
turunan_jout_jin = relu_derivatives(jin)
turunan_jout_jin

array([[ 1.,  1.,  1.,  1.]])

In [270]:
# hitung turunan jin terhadap turunan wij
turunan_jin_wij = i
turunan_jin_wij

array([[2]])

In [273]:
# hitung turunan loss terhadap turunan wij
turunan_loss_wij = turunan_loss_jout * turunan_jout_jin * turunan_jin_wij
turunan_loss_wij

array([[-0.0413771 , -0.05518954, -0.06901203, -0.08284455]])

In [274]:
# hitung turunan loss terhadap turunan bij
turunan_loss_bij = turunan_loss_jout * turunan_jout_jin * bij
turunan_loss_bij

array([[-0.02068855, -0.02759477, -0.03450601, -0.04142227]])

In [275]:
# update value wij
turunan_wij = wij - (0.25 * turunan_loss_wij)
turunan_wij

array([[ 0.26034427,  0.51379739,  0.76725301,  1.02071114]])

In [276]:
# update value bij
turunan_bij = bij - (0.25 * turunan_loss_bij)
turunan_bij

array([[ 1.00517214,  1.00689869,  1.0086265 ,  1.01035557]])

In [277]:
# perbandingan new dengan old parameter
# old paramter
wij

array([[ 0.25,  0.5 ,  0.75,  1.  ]])

In [278]:
bij

array([[1, 1, 1, 1]])

In [279]:
wjk

array([[ 1.  ,  0.  ],
       [ 0.75,  0.25],
       [ 0.5 ,  0.5 ],
       [ 0.25,  0.75]])

In [280]:
bjk

array([[1, 1]])

In [281]:
wko

array([[ 1. ],
       [ 0.5]])

In [282]:
bko

array([[1]])

In [283]:
# new parameter
turunan_wij

array([[ 0.26034427,  0.51379739,  0.76725301,  1.02071114]])

In [284]:
turunan_bij

array([[ 1.00517214,  1.00689869,  1.0086265 ,  1.01035557]])

In [285]:
turunan_wjk

array([[  1.00046670e+00,   6.26288917e-04],
       [  7.50622261e-01,   2.50835052e-01],
       [  5.00777827e-01,   5.01043815e-01],
       [  2.50933392e-01,   7.51252578e-01]])

In [286]:
turunan_bjk

array([[ 1.00031113,  1.00041753]])

In [287]:
turunan_wko

array([[ 1.12614209],
       [ 0.62560842]])

In [288]:
turunan_bko

array([[ 1.12645476]])